monomer: BTBT
symmetry: glide
auto_dir: runs/BTBT_glide_bstack_test

# b-stack のみを Amber 最適化の初期点として使う
vdw_select: b-stack

parameters:
  alpha: {min: 25, max: 25, step: 1}
  phi:   {min: -10, max: 10, step: 2}
  z:     {min: -1.0, max: 1.0, step: 0.2}
  theta_c_step: 5

amber:
  num_nodes: 38
